### ISSUE TITLE
Web interface stuck in search

### ISSUE THREAD

**Issue by trischi01** [lasselukkari/DuinoDCX#260]
Hello, I flashed the DuinoDCX. Everything worked so far and I connected everything correctly. But when I open the website with the IP address it says Searching and it doesn't find the DCX can you please help me?

Best regards

**Comment by clatoverada** [comment]
I had the same problem. Several RS232 adapters broke during the test phase. This probably always happened when the ESP32 was switched off. I have now simply soldered a 1k resistor into each of the 2 data lines from the RS232 Adapter to the DCX2496. Since then, the RS232 adapters have not broken any more.

**Comment by lasselukkari** [comment]
For some reason the connection between the mcu and the dsp is not working. Swap parts or debug in some other way until you know what the problem is.

**Comment by MarkusNoll** [comment]
I had the same issues. For me the issue was, that the RS232 cable was not real nullmodem-cable (it was a direkt 1:1 cable). I needed to cut the RS232-cable in the middle and make a cross-connection between pin2 / pin 3.
